var lineecharts1=echarts.init(document.getElementById('line1'));
var option2={
	xAxis:{
		data:['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],
		axisTick:{
			show:false
		},
		axisLine:{
			show:false
		}
	},
	yAxis:{
		splitline:{
			lineStyle:{
				color:'#012f4a'
			}
		}
	},
	series:[{
		name:'新增粉丝',
		data:[24,40,101,134,90,230,120,230,210,120],
		type:'line',
		smooth:true
	},{
		name:'新增游客',
		data:[24,40,101,60,90,45,120,230,89,195],
		type:'line',
		smooth:true
	}],
	color:['#00f2f1','#ed3f35'],
	grid:{
		top:'20%',
		left:'3%',
		right:'4%',
		bottom:'3%',
		containLabel:true,
		show:true,
		borderColor:'#012f4a'
	},
	legend:{
		data:['新增粉丝','新增游客'],
		right:'10%'
	},
	toolbox:{
		show:true,
		feature:{
			saveAsImage:{
				show:true
			}
		}
	}
}
lineecharts1.setOption(option2);